### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by lsquser** [gim4855744/XIN#1]
Hi! 
I am very interested to know which paper's code this is. Also, I did not find the HONAM code in your repository and ask for help.

**Comment by gim4855744** [comment]
- This repository contains the source code of eXtreme Interaction Network (XIN), which is proposed in our paper, "Combining Multiple Implicit-Explicit Interactions for Regression Analysis" (https://doi.org/10.1109/BigData50022.2020.9378402).
- The source code of HONAM has now been publicly opened.

**Comment by lsquser** [comment]
Thank you very much for your reply!
